#!/usr/bin/perl

# moat14
# John Jacobsen, NPX Designs, Inc., jacobsen\@npxdesigns.com
# Started: Sun Jan 16 16:21:24 2005

use strict;
my $args = join ' ', @ARGV;
my $cmd = "moat -d 10 -c 600 -g -r 3600 -t 3600 -a 21600 -e $args";
print "$cmd\n";
exec $cmd;
__END__

