#!/usr/bin/perl

# tagtools
# John Jacobsen, NPX Designs, Inc., jacobsen\@npxdesigns.com
# $Id: tagmoat,v 1.5 2010-03-09 18:49:22 jacobsen Exp $

use strict;

print "Welcome to $0.\n";

my $project = "moat";
my $tag = undef;
my $deliver;

do {
    my $log = `cvs log Makefile | grep V | head`;
    print "List of recent existing tags:\n$log\n";
    my $default = "";
    if($log =~ /(\d\d)-(\d\d)-(\d\d)/) {
	my $major = $1;
	my $minor = $2;
	my $bug = $3;
	$bug += 1;
	$default = sprintf "V%02d-%02d-%02d", $major, $minor, $bug;
    }
    my $defstr = "";
    if($default ne "") {
	$defstr = " [$default]";
    }
    print "Enter tag name$defstr: ";
    $tag = <STDIN>; 
    chomp $tag;
    if($tag eq "") {
	$tag = $default; 
    }
} until defined $tag;

print "Create new release with release tag \"$tag\"? ";
chomp(my $resp = <STDIN>);
exit if($resp !~ /^y/i);

print "Did you update RELEASE_NOTES for $tag? ";
chomp(my $resp = <STDIN>);
exit if($resp !~ /^y/i);

my $verFile = "$project"."-version";
die "Can't find current $verFile!  Old version of $project?\n" unless -f $verFile;
print "Updating $verFile...\n";
print `cvs update -A $verFile`;

sub create_verfile {
    my $tag = shift;
    print "Creating new $verFile...\n";
    open H, ">$verFile" || die "Can't open $verFile: $!\n";
    print H "$tag\n";
    close H;
    print "New $verFile is:\n".`cat $verFile`;
}
create_verfile $tag;

print "Result of cvs diff --brief:\n".`cvs diff --brief`;

print "Commit current version of project '$project' to CVS? ";
chomp(my $resp = <STDIN>);
if($resp =~ /^y/i) {
    print `cvs commit -m "Tagging current version as $tag..."`;
}

print "Tag current release as $tag? ";
chomp(my $resp = <STDIN>);
if($resp =~ /^y/i) {
    print `cd ..; cvs tag $tag $project; cd $project`;
}

print "\n\nDone.\n";


__END__

